new TypeIt('#typeit-text', {
    speed: 100,
    waitUntilVisible: true,
    loop: true
})  
    .type('Student')
    .pause(2000)
    .delete()
    .pause(500)
    .type('Developer')
    .pause(2000)
    .delete()
    .pause(500)
    .type('JavaScript programmer')
    .pause(2000)
    .delete()
    .pause(500)
    .type('Vim user')
    .pause(2000)
    .delete()
    .pause(500)
    .type('Swift learner')
    .pause(2000)
    .delete()
    .pause(500)
    .type('Learning new technologies')
    .pause(2000)
    .delete()
    .pause(500)
    .go()